server:
  port:         8080
  readTimeout:  10s
  writeTimeout: 10s
  idleTimeout:  60s

log:
  format: "json"
  level: debug

jwt:
  secret: "your-dev-secret-here"

aws:
  region:          us-east-1
  accessKeyId:     test
  secretAccessKey: test

sqs:
  endpoint:          http://localhost:4566
  account:           "000000000000"
  bulkOrderQueueUrl: http://localhost:4566/000000000000/CreateBulkOrder
  consumer:
    workerCount:         1
    concurrencyPerWorker: 1
    batchSize:           1
    visibilityTimeout:   30

mongo:
  uri: mongodb://localhost:27017/omsdb

redis:
  addrs: [localhost:6379]

kafka:
  brokers:
    - localhost:9092
  clientId: "oms-producer"
  groupId:          "webhook-dispatcher-group"
  topicOrderCreated: "order.created"
  topicOrderUpdated: "order.updated"
  topicWebhookFailed: "webhook.failed"
  version: "2.8.0"
  
finalizer:
  groupID:  "oms-finalizer-group"
  clientID: "oms-finalizer"
  topicCreated:     "order.created"
  topicUpdated:     "order.updated"


postgres:
  uri: postgres://postgres:password@localhost:5432/omsdb?sslmode=disable

env: development

s3:
  endpoint:     http://localhost:4566
  region:       us-east-1
  uploadBucket: my-bucket

ims:
  baseUrl: http://localhost:8081
